version: "3"

services:
  sample-server:
    image: sample-server
    container_name: my-server
    ports:
      - 8080:8080
      - 8000:8000

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
    ports:
      - 127.0.0.1:9090:9090
      
  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    ports:
      - 9091:9091

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
